Test cases
teragrep/jla_01 pull request #38
Opened 2024-11-25 14:19 UTC by kortemik

2024-11-25 14:34 UTC, StrongestNumber9 requested changes
Changes looks overall good but:

Getting these from the `com.teragrep.jla_01.RlpLogbackAppenderTest` test:
```
WARN  [IngressImpl] - End of stream for PeerAddress </127.0.0.1> PeerPort <53376>. Closing Connection.
WARN  [IngressImpl] - End of stream for PeerAddress </127.0.0.1> PeerPort <41390>. Closing Connection.
```

Add test that sends multiple messages and see if everything comes as expected

2024-11-25 14:34 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/jla_01/RlpLogbackAppenderTest.java
> +	public void testDefaultSyslogMessage() throws Exception {
Don't throw exceptions in tests

2024-11-25 14:34 UTC, StrongestNumber9 commented on src/test/java/com/teragrep/jla_01/RlpLogbackAppenderTest.java
> +		final int serverPort = 22602;
You should not need distinct port for each of the tests

2024-11-26 09:01 UTC, kortemik commented on src/test/java/com/teragrep/jla_01/RlpLogbackAppenderTest.java
> +		final int serverPort = 22602;
in case tests are run in parallel they need dedicated port

2024-11-26 09:05 UTC, kortemik commented on src/test/java/com/teragrep/jla_01/RlpLogbackAppenderTest.java
> +	public void testDefaultSyslogMessage() throws Exception {
removed in [c9aef8f](https://github.com/teragrep/jla_01/pull/38/commits/c9aef8fcf40ff9b55f30122330cb17a66fe66203)

2024-11-26 09:09 UTC, kortemik commented on src/test/java/com/teragrep/jla_01/RlpLogbackAppenderTest.java
> +	public void testDefaultSyslogMessage() throws Exception {
and [79c7f17](https://github.com/teragrep/jla_01/pull/38/commits/79c7f17b9b2df426502f79bdcde53f04a37dee89)

2024-11-26 10:02 UTC, StrongestNumber9 approved these changes
lgtm

2024-11-26 10:05 UTC, kortemik commented
> Changes looks overall good but:
> 
> Getting these from the `com.teragrep.jla_01.RlpLogbackAppenderTest` test:
> 
> ```
> WARN  [IngressImpl] - End of stream for PeerAddress </127.0.0.1> PeerPort <53376>. Closing Connection.
> WARN  [IngressImpl] - End of stream for PeerAddress </127.0.0.1> PeerPort <41390>. Closing Connection.
> ```
> 
> Add test that sends multiple messages and see if everything comes as expected

tcpdump indicates that relp connection is opened twice:
```
1 open 53 
relp_version=0
relp_software=RLP-01
commands=syslog

1 rsp 86 200 OK
relp_version=0
relp_software=rlp_03,9.0.0,https://teragrep.com
commands=syslog

1 open 53 
relp_version=0
relp_software=RLP-01
commands=syslog

1 rsp 86 200 OK
relp_version=0
relp_software=rlp_03,9.0.0,https://teragrep.com
commands=syslog

2 syslog 75 <12>1 2024-11-26T10:00:12.366Z localhost appName - - - DEBUG logger - none

2 rsp 6 200 OK

3 close 0

3 rsp 0 
0 serverclose 0 
```

2024-11-26 10:07 UTC, kortemik commented
created https://github.com/teragrep/jla_01/issues/39

2024-11-26 10:07 UTC, merged